# Laptop interno
monitor=eDP-1,1920x1200@60,0x0,1.0

# Samsung central (HDMI)
monitor=HDMI-A-1,1920x1080@60,1920x0,1.0

# Monitor vertical derecha — DP-1 en laptop, DP-2 en desktop
monitor=DP-1,1920x1080@60,3840x0,1.0,transform,1
monitor=DP-2,1920x1080@60,3840x0,1.2,transform,1

# Fallback para monitores no declarados
monitor=,preferred,auto,1.0
